# Allow build scripts to be referenced without being copied into the final image
FROM scratch AS ctx
COPY build_files/granite /

# Base Image - AlmaLinux Atomic Desktop KDE (pinned to major version 10)
FROM quay.io/almalinuxorg/atomic-desktop-kde:10

### MODIFICATIONS
RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache \
    bash /ctx/build.sh

### LINTING
## Verify final image and contents are correct.
RUN bootc container lint
